# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: å…”å­å¿«è·‘
subtitle:
description: åšå®¢ å…”å­å¿«è·‘ 
keywords: å…”å­å¿«è·‘ å…”å­æ€ä¹ˆä¼šåœ å…”å­ä¸è¦åœä¸‹
author: RunRabbit
language: zh-CN 
timezone:

# URL
url: https://www.runrab.com
root: /
#permalink: :year/:month/:day/:title/
permalink: archives/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true
abbrlink:
  alg: crc32 # ç®—æ³•ï¼šcrc16(default) and crc32
  rep: hex # è¿›åˆ¶ï¼šdec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
#external_link: true # Open external links in new tab
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 20
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#deploy:
#  type:
 
deploy:
  - type: git
    repository:
      github: https://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@github.com/runrab/runrab.github.io.git
      #coding: https://username:password@e.coding.net/owner/repo
    branch: master  
#RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
#è¿½ç•ª
bangumi:
  enable: true
  path: /bangumis/index.html
  vmid: 406109915
  title: 'è¿½ç•ªåˆ—è¡¨'
  quote: 'ç”Ÿå‘½ä¸æ¯ï¼Œè¿½ç•ªä¸æ­¢ï¼'
  show: 1
  loading: '/lab/img/bangumi-loading.gif' 
  metaColor:
  color:
  webp: true
  progress: true  
#diy by myself
# ä¸Šé¢çš„å†…å®¹ä¸€èˆ¬éƒ½æœ‰ï¼Œä¸»è¦æ˜¯ä¸‹é¢çš„
archive_generator:  # å½’æ¡£é¡µé¢
  per_page: 30      # æ¯ä¸ªåˆ†é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡ï¼Œå€¼ä¸º0è¡¨ç¤ºä¸åˆ†é¡µï¼ŒæŒ‰éœ€å¡«å†™
  yearly: true      # æ˜¯å¦æŒ‰å¹´ç”Ÿæˆå½’æ¡£
  monthly: true    # æŒ‰æœˆå½’æ¡£å°±è¦

tag_generator:      # æ ‡ç­¾é¡µé¢
  per_page: 30      # æ¯ä¸ªåˆ†é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡ï¼Œå€¼ä¸º0è¡¨ç¤ºä¸åˆ†é¡µï¼ŒæŒ‰éœ€å¡«å†™

category_generator: # åˆ†ç±»é¡µé¢
  per_page: 00      # æ¯ä¸ªåˆ†é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡ï¼Œå€¼ä¸º0è¡¨ç¤ºä¸åˆ†é¡µï¼ŒæŒ‰éœ€å¡«å†™   

# Ice Kano Plus_in
# Hexo Github Canlendar
# Volantis
# Matery
# butterfly
githubcalendar:
  enable: true
  priority: 1
  enable_page: /
  user: runrab
  layout:
    type: id
    name: recent-posts
    index: 0
  githubcalendar_html: '<div class="recent-post-item" style="width:100%;height:auto;padding:10px;"><div id="github_loading" style="height:100%;display: flex;align-items: center;justify-content: center;"><svg style="height:50px" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"  viewBox="0 0 50 50" style="enable-background:new 0 0 50 50" xml:space="preserve"><path fill="#d0d0d0" d="M25.251,6.461c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615V6.461z" transform="rotate(275.098 25 25)"><animateTransform attributeType="xml" attributeName="transform" type="rotate" from="0 25 25" to="360 25 25" dur="0.6s" repeatCount="indefinite"></animateTransform></path></svg></div><div id="github_container"></div></div>'
  pc_minheight: 248px
  mobile_minheight: 0px
  color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']"
  api: https://calendar.runrab.com/api #https://python-github-calendar-api.vercel.app/api
  # api: https://python-gitee-calendar-api.vercel.app/api
  calendar_js: https://cdn.jsdelivr.net/gh/Zfour/hexo-github-calendar@1.21/hexo_githubcalendar.js
  plus_style: ""
#hexo-magnet æ’ä»¶
magnet:
  enable: false
  priority: 3
  enable_page: /
  type: categories
  devide: 2
  display:
    - name: æ•™ç¨‹
      display_name: å…”å­å¿«è·‘ã®æ•™ç¨‹
      icon: ğŸ“š
    - name: é­”æ”¹ä¸»é¢˜
      display_name: å…”å­å¿«è·‘ã®é­”æ”¹ä¸»é¢˜
      icon: ğŸ®
    - name: å¤§æ•°æ®
      display_name: å…”å­å¿«è·‘ã®å¤§æ•°æ®
      icon: ğŸ±â€ğŸ‘“
    - name: Java
      display_name: å…”å­å¿«è·‘ã®Java
      icon: ğŸ‘©â€ğŸ’»
    - name: Python
      display_name: å…”å­å¿«è·‘ã®Python
      icon: ğŸ“’
    - name: mysql
      display_name: å…”å­å¿«è·‘ã®mysql
      icon: ğŸ’¡
  color_setting:
    text_color: black
    text_hover_color: white
    background_color: "#f2f2f2"
    background_hover_color: "#b30070"
  layout:
    type: id
    name: recent-posts
    index: 0
  temple_html: '<div class="recent-post-item" style="width:100%;height: auto"><div id="catalog_magnet">${temple_html_item}</div></div>'
  plus_style: ""

# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # å¼€å…³
  priority: 4 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: all # åº”ç”¨é¡µé¢
  timemode: date #date/updated
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: id
    name: recent-posts
    index: 0
  default_descr: å†æ€ä¹ˆçœ‹æˆ‘ä¹Ÿä¸çŸ¥é“æ€ä¹ˆæè¿°å®ƒçš„å•¦ï¼

butterfly_article_double_row:
  enable: true

history_calendar:
  priority: 6
  enable: true
  enable_page: all
  layout:
    type: class
    name: sticky_layout
    index: 0
  temple_html: '<div class="card-widget card-history"><div class="card-content"><div class="item-headline"><i class="fas fa-clock fa-spin"></i><span>é‚£å¹´ä»Šæ—¥</span></div><div id="history-baidu" style="height: 100px;overflow: hidden"><div class="history_swiper-container" id="history-container" style="width: 100%;height: 100%"><div class="swiper-wrapper" id="history_container_wrapper" style="height:20px"></div></div></div></div>'

electric_clock:
  priority: 7
  enable: true
  enable_page: all
  layout:
    type: class
    name: sticky_layout
    index: 0
  temple_html: '<div class="card-widget card-clock"><div class="card-glass"><div class="card-background"><div class="card-content"><div id="hexo_electric_clock"><img id="card-clock-loading" src="https://cdn.jsdelivr.net/gh/Zfour/Butterfly-clock/clock/images/weather/loading.gif" style="height: 120px; width: 100%;" data-ll-status="loading" class="entered loading"></div></div></div></div></div>'  
 
#npm install hexo-all-minifier --save 
all_minifier: true
# htmlå‹ç¼©
html_minifier:
  enable: true
  ignore_error: false
  exclude:

# csså‹ç¼©
css_minifier:
  enable: true
  exclude:
    - '*.min.css'
    - '*.css'
    
# jså‹ç¼©
js_minifier:
  enable: true
  mangle: true
  compress:
  exclude:
    - '*.min.js'
    - '*.js'
js_concator:
  enable: false
  bundle_path: '/js/bundle.js'
  front: false
  silent: false

# å›¾ç‰‡ä¼˜åŒ– ä¼šæŠ¥é”™ç›´æ¥å…³é—­
image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false
#æ–‡ç« åŠ å¯† hexo-blog-encrypt
encrypt:
    enable: true
# ç™¾åº¦ä¸»åŠ¨æ¨é€
baidu_url_submit:
  count: 20 ## æäº¤æœ€æ–°çš„1ä¸ªé“¾æ¥
  host: www.runrab.com ## ç™¾åº¦ç«™é•¿å¹³å°ä¸­æ³¨å†Œçš„åŸŸå
  token: UXvHSTrz0lKJwHtJ ## å‡†å…¥ç§˜é’¥
  path: baidu_urls.txt ## æ–‡æœ¬æ–‡æ¡£çš„åœ°å€ï¼Œ æ–°é“¾æ¥ä¼šä¿å­˜åœ¨æ­¤æ–‡æœ¬æ–‡æ¡£é‡Œ
# ç™¾åº¦ç«™ç‚¹åœ°å›¾
baidusitemap:
  path: baidusitemap.xml  
#ç›¸å…³æ–‡ç« æ¨è  
#related_posts:
#  enable: false
#  title: ç›¸å…³æ–‡ç« æ¨è # Custom header, leave empty to use the default one
#  display_in_home: true
#  params:
#    maxCount: 6
#    PPMixingRate: 0.25
#    isDate: true
#    isImage: false
#    isExcerpt: false
#å‡å°‘å¤–é“¾    hexo-filter-nofollow  
nofollow:
  enable: true
  field: site
  exclude:
    - 'netapi.top'
    - 'sssj.top'
# artitalk see https://artitalk.js.org/
# hexo-butterfly-artitalk-pro
# see https://akilar.top/posts/f1004b1d/
artitalk:
  enable:
    card: true # ä¾§è¾¹æ å¼€å…³
    page: true #é¡µé¢å¼€å…³
  # ä¾§æ ç›¸å…³é…ç½®é¡¹
  priority: 8 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: all # åº”ç”¨é¡µé¢
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: class
    name: sticky_layout
    index: 0
  # é¡µé¢ç›¸å…³é…ç½®é¡¹
  path: artitalk
  front_matter:
    title: ç¢ç¢å¿µ
  # å…¬å…±é…ç½®é¡¹
  appId: Q6eWOea6YF3UegICqQb577G5-MdYXbMMI
  appKey: 9jYrbplmnwzHiWnJFX6WwKaj
  exclude: /artitalk/
  js: https://cdn.jsdelivr.net/npm/artitalk
  option:
    #serverURL: https://********.api.lncldglobal.com
    lang: zh
    pageSize: 1
    color1: '#49b1f5'
    color2: '#00c4b6'
    atEmoji: {
      'Mafumafu1':'https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Mafumafu/199749454.png',
      'Mafumafu2':'https://cdn.jsdelivr.net/gh/GamerNoTitle/ValineCDN@master/Mafumafu/199749455.png'}    
#bç«™åŒæ¬¾ banneræ ·å¼
#bilibili_banner:
#  enable: true # å¼€å…³banner
#  style: autumn  # autumn ç§‹å­£æ ·å¼ ï¼›winter å†¬å­£æ ·å¼
# hexo-butterfly-envelope
envelope_comment:
  enable: true
  cover: https://ae01.alicdn.com/kf/U5bb04af32be544c4b41206d9a42fcacfd.jpg # ä¿¡ç¬ºå°é¢å›¾
  message:  # ä¿¡ç¬ºå†…å®¹ï¼Œæ”¯æŒå¤šè¡Œ
    - æœ‰ä»€ä¹ˆæƒ³é—®çš„ï¼Ÿ
    - æœ‰ä»€ä¹ˆæƒ³è¯´çš„ï¼Ÿ
    - æœ‰ä»€ä¹ˆæƒ³åæ§½çš„ï¼Ÿ
  bottom: è‡ªåŠ¨ä¹¦è®°äººå¶ç«­è¯šä¸ºæ‚¨æœåŠ¡ï¼   # ä¿¡ç¬ºç»“æŸè¯­ï¼Œåªèƒ½å•è¡Œ
  height:                          # è°ƒæ•´ä¿¡ç¬ºåˆ’å‡ºé«˜åº¦ï¼Œé»˜è®¤1050px
  path: /comments                # ã€å¯é€‰ã€‘comments çš„è·¯å¾„åç§°ã€‚é»˜è®¤ä¸º comments ï¼Œ ç”Ÿæˆçš„é¡µé¢ä¸º comments/index.html
  front_matter:                    # ã€å¯é€‰ã€‘commentsé¡µé¢çš„ front_matter é…ç½®
    title: ç•™è¨€
    comments: true
    aside: false